/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe (no DB access).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meta
         * @description Athlete, season position, data version and last job runs.
         */
        get: operations["get_meta_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fitness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fitness
         * @description Daily load and CTL/ATL/TSB (default: last 120 days).
         */
        get: operations["get_fitness_v1_fitness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/season": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Season
         * @description Season skeleton with weekly targets projected from current fitness.
         */
        get: operations["get_season_v1_season_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trends/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trends
         * @description Last trends report (PMC agreement, CP fits, durability, TID, climbs, limiters).
         */
        get: operations["get_trends_v1_trends_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trends/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute Trends
         * @description Recompute and store the trends report (~100 ms).
         */
        post: operations["recompute_trends_v1_trends_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Explanation
         * @description The persisted Explanation for ``key`` (e.g. ``ride:42``, ``readiness.2026-10-06``).
         */
        get: operations["get_explanation_v1_explain__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Glossary
         * @description Glossary term ids (``docs/glossary/*.md``).
         */
        get: operations["list_glossary_v1_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/glossary/{term}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Glossary
         * @description One glossary page as Markdown (zh-TW).
         */
        get: operations["get_glossary_v1_glossary__term__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description Newest first; filter by date range, sport, rides only, ride class.
         */
        get: operations["list_activities_v1_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Stored per-ride analysis with its Explanation.
         */
        get: operations["get_activity_v1_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activity_id}/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Streams
         * @description Chart-ready streams (bucket-averaged; ≤ 5 000 points by default).
         */
        get: operations["get_streams_v1_activities__activity_id__streams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activity_id}/ride-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ride Log
         * @description WORKOUT + RIDE.LOG text for a Strava description (deterministic; no poem).
         */
        get: operations["ride_log_v1_activities__activity_id__ride_log_get"];
        put?: never;
        /**
         * Save Ride Log
         * @description Store the edited RIDE.LOG (e.g. with the acrostic poem); "" restores the generated one.
         */
        post: operations["save_ride_log_v1_activities__activity_id__ride_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activity_id}/strava-description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Strava Description
         * @description Preview (``confirm=false``) or write the ride's RIDE.LOG to Strava (flag-gated).
         */
        post: operations["strava_description_v1_activities__activity_id__strava_description_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activities/{activity_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback
         * @description Post-ride RPE / feel: the web answer, else intervals.icu's.
         */
        get: operations["get_feedback_v1_activities__activity_id__feedback_get"];
        put?: never;
        /**
         * Save Feedback
         * @description Store post-ride RPE / feel; readiness is recomputed for the next day right away.
         */
        post: operations["save_feedback_v1_activities__activity_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ftp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ftp
         * @description Current FTP, MMP, CP fits vs icu, estimate series and the (never applied) proposal.
         */
        get: operations["get_ftp_v1_ftp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ftp/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What If
         * @description Same as ``GET /ftp`` but evaluated against another FTP setting (nothing stored).
         */
        post: operations["what_if_v1_ftp_what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ftp/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept
         * @description Record the athlete's FTP decision (manual settings row; icu is not changed).
         */
        post: operations["accept_v1_ftp_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Stored verdicts (default: last 28 days).
         */
        get: operations["history_v1_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readiness/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Day
         * @description Stored verdict, or computed on the fly when none is stored.
         */
        get: operations["get_day_v1_readiness__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readiness/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute
         * @description Score and store the given days (default: today).
         */
        post: operations["recompute_v1_readiness_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored
         * @description Stored proposals (what the calendar will get), rendered with steps and workout text.
         */
        get: operations["stored_v1_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description What-if plan (availability, days off, indoor days, readiness, bias, CTL); nothing stored.
         */
        post: operations["preview_v1_plan_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit
         * @description Replan and store proposals (never writes to intervals.icu); 409 while a run is active.
         */
        post: operations["commit_v1_plan_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description Stored report stems, newest first (``2026-10-06`` / ``2026-W41``).
         */
        get: operations["list_reports_v1_reports__kind__get"];
        put?: never;
        /**
         * Build Report
         * @description Render (and store) the report for ``day`` (default today / this week).
         */
        post: operations["build_report_v1_reports__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/{kind}/{stem}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Markdown + structured facts of one report.
         */
        get: operations["get_report_v1_reports__kind___stem__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Queue a job (one runs at a time); poll ``GET /jobs/{id}``.
         */
        post: operations["start_v1_jobs__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description This profile's jobs started by this server process.
         */
        get: operations["list_jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Status / result of one job.
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description Every profile with its mode, last run and whether the UI may write its calendar.
         */
        get: operations["list_profiles_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/autopilot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Queue this profile's morning run; poll ``GET /v1/jobs/{id}`` for the report.
         */
        post: operations["run_v1_autopilot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/autopilot/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs
         * @description Saved run reports (scheduled and manual), newest first.
         */
        get: operations["runs_v1_autopilot_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityDetail
         * @description ``GET /v1/activities/{id}``: the stored per-ride analysis.
         */
        ActivityDetail: {
            summary: components["schemas"]["ActivitySummary"];
            /** Distance M */
            distance_m?: number | null;
            /** Elev Gain M */
            elev_gain_m?: number | null;
            /** Avg W */
            avg_w?: number | null;
            /** Avg Hr */
            avg_hr?: number | null;
            /** Max Hr */
            max_hr?: number | null;
            /** Vi */
            vi?: number | null;
            /** Hr Lag S */
            hr_lag_s?: number | null;
            /** Power Curve */
            power_curve?: {
                [key: string]: number;
            };
            /** Time In Zone Power */
            time_in_zone_power?: {
                [key: string]: number;
            } | null;
            /** Time In Zone Hr */
            time_in_zone_hr?: {
                [key: string]: number;
            } | null;
            /** Climbs */
            climbs?: {
                [key: string]: unknown;
            }[];
            /** Efforts */
            efforts?: {
                [key: string]: unknown;
            }[];
            /** Pacing */
            pacing?: {
                [key: string]: unknown;
            };
            /** Durability */
            durability?: {
                [key: string]: unknown;
            } | null;
            /** Next Recommendation */
            next_recommendation?: string | null;
            explanation?: components["schemas"]["Explanation"] | null;
            /**
             * Has Streams
             * @default false
             */
            has_streams: boolean;
        };
        /**
         * ActivityPage
         * @description ``GET /v1/activities``.
         */
        ActivityPage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Items */
            items: components["schemas"]["ActivitySummary"][];
        };
        /**
         * ActivitySummary
         * @description Row of the activity list.
         */
        ActivitySummary: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Name */
            name: string | null;
            /** Sport */
            sport: string;
            /** Is Ride */
            is_ride: boolean;
            /** Moving S */
            moving_s: number;
            /** Load */
            load: number;
            /** Load Source */
            load_source: string;
            /** Tss */
            tss?: number | null;
            /** Np W */
            np_w?: number | null;
            /** Intensity Factor */
            intensity_factor?: number | null;
            /** Ef */
            ef?: number | null;
            /** Decoupling Pct */
            decoupling_pct?: number | null;
            /** Classification */
            classification?: string | null;
            /** Classification Zh */
            classification_zh?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Climbs
             * @default 0
             */
            climbs: number;
        };
        /**
         * AthleteSummary
         * @description Who the data belongs to and their current anchors.
         */
        AthleteSummary: {
            /** Athlete Id */
            athlete_id: number;
            /** Name */
            name?: string | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /**
             * Ftp
             * @description FTP effective today (W)
             */
            ftp?: number | null;
            /** W Kg */
            w_kg?: number | null;
            /** Timezone */
            timezone: string;
        };
        /**
         * AutopilotRequest
         * @description ``POST /v1/autopilot``: run the morning now. ``write`` needs ``confirm``.
         */
        AutopilotRequest: {
            /**
             * Write
             * @default false
             */
            write: boolean;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /**
         * AutopilotRunOut
         * @description ``GET /v1/autopilot/runs``: a saved run report.
         */
        AutopilotRunOut: {
            /** Profile */
            profile: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Planner Mode */
            planner_mode: string;
            /** Ok */
            ok: boolean;
            /** At */
            at?: string | null;
            /** Stages */
            stages?: components["schemas"]["AutopilotStage"][];
        };
        /**
         * AutopilotStage
         * @description One stage of an autopilot run.
         */
        AutopilotStage: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** Body_recompute_v1_readiness_recompute_post */
        Body_recompute_v1_readiness_recompute_post: {
            /** Dates */
            dates?: string[] | null;
        };
        /**
         * CPFitOut
         * @description One CP model fit.
         */
        CPFitOut: {
            /** Cp */
            cp: number;
            /** W Prime */
            w_prime: number;
            /** P Max */
            p_max?: number | null;
            /** R2 */
            r2?: number | null;
            /** Rmse W */
            rmse_w?: number | null;
            /** Eftp */
            eftp: number;
            /** Points */
            points: number[][];
            /** Cp Diff Vs Icu Pct */
            cp_diff_vs_icu_pct?: number | null;
        };
        /**
         * EstimatePoint
         * @description Daily FTP estimate.
         */
        EstimatePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Ftp */
            ftp: number;
        };
        /**
         * ExplainOut
         * @description ``GET /v1/explain/{key}``.
         */
        ExplainOut: {
            /** Key */
            key: string;
            /** Source */
            source: string;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
        };
        /**
         * Explanation
         * @description Human-readable, machine-checkable justification of a result.
         */
        Explanation: {
            /** Key */
            key: string;
            /** Headline Zh */
            headline_zh: string;
            /** Because */
            because?: components["schemas"]["Reason"][];
            method?: components["schemas"]["MethodRef"] | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Glossary Terms */
            glossary_terms?: string[];
        };
        /**
         * FitnessPoint
         * @description One day of the performance-management chart.
         */
        FitnessPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Load
             * @description Actual daily load (all sports)
             */
            load: number;
            /** Ctl */
            ctl?: number | null;
            /** Atl */
            atl?: number | null;
            /** Tsb */
            tsb?: number | null;
            /**
             * Source
             * @default none
             * @enum {string}
             */
            source: "icu" | "sim" | "none";
            /** Ctl Sim */
            ctl_sim?: number | null;
            /** Acwr */
            acwr?: number | null;
            /** Monotony */
            monotony?: number | null;
            /**
             * Planned Load
             * @description Our proposed load for that day
             */
            planned_load?: number | null;
        };
        /**
         * FitnessSeries
         * @description ``GET /v1/fitness``.
         */
        FitnessSeries: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Points */
            points: components["schemas"]["FitnessPoint"][];
        };
        /**
         * FtpAccept
         * @description Request body of ``POST /v1/ftp/accept`` (the athlete's explicit decision).
         */
        FtpAccept: {
            /** Ftp */
            ftp: number;
            /** Effective From */
            effective_from?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * FtpProposalOut
         * @description A suggested FTP change — never applied automatically.
         */
        FtpProposalOut: {
            /** Proposed Ftp */
            proposed_ftp: number | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "none";
            /** Days Sustained */
            days_sustained: number;
            /** Median Estimate */
            median_estimate: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Best 20Min W */
            best_20min_w: number | null;
            /** Unsupported */
            unsupported: boolean;
            /**
             * Insufficient Evidence
             * @default false
             */
            insufficient_evidence: boolean;
            /** Sources */
            sources: string[];
        };
        /**
         * FtpStatusOut
         * @description ``GET /v1/ftp`` / ``POST /v1/ftp/what-if``.
         */
        FtpStatusOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Current Ftp */
            current_ftp: number | null;
            /** W Kg */
            w_kg: number | null;
            /** Windows */
            windows: {
                [key: string]: components["schemas"]["PowerWindow"];
            };
            /** Estimate Source */
            estimate_source: string;
            /** Max Efforts */
            max_efforts?: {
                [key: string]: unknown;
            } | null;
            /**
             * Power Unreliable Excluded
             * @default 0
             */
            power_unreliable_excluded: number;
            /** Estimates */
            estimates: components["schemas"]["EstimatePoint"][];
            proposal: components["schemas"]["FtpProposalOut"] | null;
            /** History */
            history: {
                [key: string]: unknown;
            }[];
            /** Explanations */
            explanations: components["schemas"]["Explanation"][];
            /** Compute Ms */
            compute_ms?: number | null;
        };
        /**
         * FtpWhatIf
         * @description Request body of ``POST /v1/ftp/what-if``.
         */
        FtpWhatIf: {
            /** As Of */
            as_of?: string | null;
            /** Ftp */
            ftp?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobOut
         * @description A background job (sync / analyze / recompute).
         */
        JobOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "ok" | "failed";
            /**
             * Profile
             * @default
             */
            profile: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /**
         * Meta
         * @description ``GET /v1/meta``: everything the app shell needs on load.
         */
        Meta: {
            /** Version */
            version: string;
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Data Version */
            data_version: string;
            athlete: components["schemas"]["AthleteSummary"] | null;
            season?: components["schemas"]["SeasonSummary"] | null;
            /** Last Jobs */
            last_jobs?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Plan Mode
             * @default propose
             * @enum {string}
             */
            plan_mode: "propose" | "apply";
        };
        /**
         * MethodRef
         * @description Which model/algorithm produced the result, with the inputs actually used.
         */
        MethodRef: {
            /** Model Id */
            model_id: string;
            /** Version */
            version: string;
            /** Inputs */
            inputs?: {
                [key: string]: unknown;
            };
            /** Doc */
            doc: string;
        };
        /**
         * PlanOut
         * @description ``GET /v1/plan`` and ``POST /v1/plan/preview``.
         */
        PlanOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Season Key */
            season_key: string;
            /** Persisted */
            persisted: boolean;
            /** Days */
            days: components["schemas"]["PlannedDayOut"][];
            /** Weeks */
            weeks: components["schemas"]["WeekTargetOut"][];
            /** Adaptations */
            adaptations: components["schemas"]["Explanation"][];
            /** Repairs */
            repairs: components["schemas"]["Explanation"][];
            /** Violations */
            violations: {
                [key: string]: unknown;
            }[];
            /** Needs Review */
            needs_review: boolean;
            /**
             * Projection
             * @description Simulated CTL/ATL/TSB over the horizon
             */
            projection?: components["schemas"]["FitnessPoint"][];
            /** Changes */
            changes?: {
                [key: string]: string[];
            };
            /** Compute Ms */
            compute_ms?: number | null;
        };
        /**
         * PlanPreviewRequest
         * @description What-if inputs for ``POST /v1/plan/preview`` (nothing is stored).
         */
        PlanPreviewRequest: {
            /** Today */
            today?: string | null;
            /** Weekday Minutes */
            weekday_minutes?: {
                [key: string]: number;
            };
            /** Weekly Max Minutes */
            weekly_max_minutes?: number | null;
            /**
             * Date Minutes
             * @description Cap minutes on dates; 0 = day off
             */
            date_minutes?: {
                [key: string]: number;
            };
            /** Indoor Days */
            indoor_days?: string[];
            /** Readiness */
            readiness?: ("REST" | "EASY" | "AS_PLANNED" | "UPGRADE") | null;
            /** Bias */
            bias?: {
                [key: string]: number;
            } | null;
            /** Horizon Days */
            horizon_days?: number | null;
            /** Ctl */
            ctl?: number | null;
            /** Atl */
            atl?: number | null;
        };
        /**
         * PlanStep
         * @description A rendered workout step (for the workout-profile chart).
         */
        PlanStep: {
            /** Kind */
            kind: string;
            /** Duration S */
            duration_s: number;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
            /** Cadence */
            cadence?: string | null;
            /** Cue */
            cue?: string | null;
            /**
             * Repeat
             * @default 1
             */
            repeat: number;
        };
        /**
         * PlannedDayOut
         * @description One day of the horizon.
         */
        PlannedDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Role */
            role: string;
            /** Role Zh */
            role_zh: string;
            /** Template Id */
            template_id?: string | null;
            /** Name Zh */
            name_zh?: string | null;
            /** Intent */
            intent: string;
            /** Tss */
            tss: number;
            /** Minutes */
            minutes: number;
            /** Max Minutes */
            max_minutes: number;
            /** Outdoor */
            outdoor: boolean;
            /** Params */
            params?: {
                [key: string]: number;
            };
            /** Steps */
            steps?: components["schemas"]["PlanStep"][];
            /** Workout Text */
            workout_text?: string | null;
            /** Note Zh */
            note_zh?: string | null;
            /**
             * Mutable
             * @default true
             */
            mutable: boolean;
            explanation?: components["schemas"]["Explanation"] | null;
        };
        /**
         * PowerWindow
         * @description Mean-maximal power + fits for one window.
         */
        PowerWindow: {
            /** Window */
            window: string;
            /** Mmp */
            mmp: {
                [key: string]: number;
            };
            cp_2p?: components["schemas"]["CPFitOut"] | null;
            cp_3p?: components["schemas"]["CPFitOut"] | null;
            /** Icu */
            icu?: {
                [key: string]: number | null;
            } | null;
        };
        /**
         * ProfileOut
         * @description ``GET /v1/profiles``: one athlete profile (no secrets).
         */
        ProfileOut: {
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Default */
            default: boolean;
            /** Icu Athlete Id */
            icu_athlete_id?: string | null;
            /** Planner Mode */
            planner_mode?: string | null;
            /** Key Set */
            key_set: boolean;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Status */
            last_run_status?: string | null;
            /** Garmin Upload Workouts */
            garmin_upload_workouts?: boolean | null;
            /**
             * Calendar Write Allowed
             * @default false
             */
            calendar_write_allowed: boolean;
            /**
             * Strava Write Allowed
             * @default false
             */
            strava_write_allowed: boolean;
        };
        /**
         * ReadinessComponentOut
         * @description One weighted input of the readiness score.
         */
        ReadinessComponentOut: {
            /** Name */
            name: string;
            /** Name Zh */
            name_zh: string;
            /** Z */
            z: number;
            /**
             * Share
             * @description Renormalised weight in the score (0–1)
             */
            share: number;
        };
        /**
         * ReadinessOut
         * @description ``GET /v1/readiness/{date}``.
         */
        ReadinessOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Score */
            score: number;
            /** Status */
            status: string;
            /** Recommendation */
            recommendation: string;
            /** Recommendation Zh */
            recommendation_zh: string;
            /** Components */
            components: components["schemas"]["ReadinessComponentOut"][];
            /** Missing */
            missing: string[];
            /** Rule Hits */
            rule_hits: string[];
            explanation?: components["schemas"]["Explanation"] | null;
        };
        /**
         * Reason
         * @description One factor behind a conclusion, most important first in ``Explanation.because``.
         */
        Reason: {
            /** Text Zh */
            text_zh: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Weight */
            weight?: number | null;
        };
        /**
         * ReportOut
         * @description ``GET /v1/reports/{kind}/{stem}``.
         */
        ReportOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "daily" | "weekly";
            /** Stem */
            stem: string;
            /** Markdown */
            markdown: string;
            /** Facts */
            facts: {
                [key: string]: unknown;
            };
        };
        /**
         * RideFeedbackIn
         * @description ``POST /v1/activities/{id}/feedback``: post-ride RPE 1–10 and feel 1 (strong) … 5 (weak).
         */
        RideFeedbackIn: {
            /** Rpe */
            rpe?: number | null;
            /** Feel */
            feel?: number | null;
        };
        /**
         * RideFeedbackOut
         * @description Answers for a ride and where they came from (``web`` / ``intervals.icu`` / ``none``).
         */
        RideFeedbackOut: {
            /** Activity Id */
            activity_id: number;
            /** Rpe */
            rpe?: number | null;
            /** Feel */
            feel?: number | null;
            /** Source */
            source: string;
        };
        /**
         * RideLogOut
         * @description ``GET /v1/activities/{id}/ride-log``: the saved text (with poem) or the generated one.
         */
        RideLogOut: {
            /** Activity Id */
            activity_id: number;
            /** Workout */
            workout: string;
            /** Ride Log */
            ride_log: string;
            /** Text */
            text: string;
            /**
             * Source
             * @default generated
             */
            source: string;
            /**
             * Generated
             * @default
             */
            generated: string;
        };
        /**
         * RideLogSave
         * @description ``POST /v1/activities/{id}/ride-log``: store an edited text ("" = back to generated).
         */
        RideLogSave: {
            /** Text */
            text: string;
        };
        /**
         * SeasonOut
         * @description ``GET /v1/season``: the whole macro plan as projected from today's CTL.
         */
        SeasonOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * Goal Date
             * Format: date
             */
            goal_date: string;
            /** Goal Name */
            goal_name: string | null;
            /** Target Ftp */
            target_ftp: number | null;
            /** Ctl Start */
            ctl_start: number;
            /** Weeks */
            weeks: components["schemas"]["SeasonWeekOut"][];
        };
        /**
         * SeasonSummary
         * @description Where today sits in the season.
         */
        SeasonSummary: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * Goal Date
             * Format: date
             */
            goal_date: string;
            /** Goal Name */
            goal_name?: string | null;
            /** Target Ftp */
            target_ftp?: number | null;
            /**
             * Week Index
             * @description 1-based season week of today
             */
            week_index?: number | null;
            /** Weeks Total */
            weeks_total: number;
            /** Phase */
            phase?: string | null;
        };
        /**
         * SeasonWeekOut
         * @description One week of the season overview.
         */
        SeasonWeekOut: {
            /** Index */
            index: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Phase */
            phase: string;
            /** Phase Zh */
            phase_zh: string;
            /** Recovery */
            recovery: boolean;
            /** Test */
            test: string | null;
            /** Hit Sessions */
            hit_sessions: number;
            /** Target Tss */
            target_tss: number;
            /** Target Hours */
            target_hours: number;
            /** Ctl End */
            ctl_end: number;
            /** Checkpoint Ftp */
            checkpoint_ftp?: number | null;
            /** Long Ride Minutes */
            long_ride_minutes?: number | null;
            /**
             * Over Distance
             * @default false
             */
            over_distance: boolean;
        };
        /**
         * StravaDescriptionOut
         * @description Result of a preview or a write.
         */
        StravaDescriptionOut: {
            /** Strava Id */
            strava_id: number;
            /** Before */
            before: string;
            /** After */
            after: string;
            /** Written */
            written: boolean;
        };
        /**
         * StravaDescriptionRequest
         * @description ``POST /v1/activities/{id}/strava-description``: preview, or write with ``confirm``.
         */
        StravaDescriptionRequest: {
            /** Text */
            text: string;
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
        };
        /**
         * StreamSeries
         * @description ``GET /v1/activities/{id}/streams``: column arrays, downsampled for charts.
         */
        StreamSeries: {
            /** Activity Id */
            activity_id: number;
            /** Resolution S */
            resolution_s: number;
            /** N */
            n: number;
            /** Columns */
            columns: {
                [key: string]: (number | null)[];
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeekTargetOut
         * @description Load target of one season week.
         */
        WeekTargetOut: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Index */
            index: number;
            /** Phase */
            phase: string;
            /** Phase Zh */
            phase_zh: string;
            /** Recovery */
            recovery: boolean;
            /** Test */
            test?: string | null;
            /** Target Tss */
            target_tss: number;
            /** Target Hours */
            target_hours: number;
            /** Ctl Start */
            ctl_start: number;
            /** Ctl End */
            ctl_end: number;
            /** Planned Tss */
            planned_tss?: number | null;
            /** Planned Hours */
            planned_hours?: number | null;
            explanation?: components["schemas"]["Explanation"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_meta_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    get_fitness_v1_fitness_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitnessSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_v1_season_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonOut"];
                };
            };
        };
    };
    get_trends_v1_trends_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recompute_trends_v1_trends_recompute_post: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explanation_v1_explain__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_glossary_v1_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_glossary_v1_glossary__term__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_v1_activities_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                sport?: string | null;
                rides_only?: boolean;
                classification?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_v1_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streams_v1_activities__activity_id__streams_get: {
        parameters: {
            query?: {
                resolution_s?: number | null;
            };
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ride_log_v1_activities__activity_id__ride_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_ride_log_v1_activities__activity_id__ride_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideLogSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strava_description_v1_activities__activity_id__strava_description_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StravaDescriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StravaDescriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_v1_activities__activity_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideFeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_feedback_v1_activities__activity_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RideFeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideFeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ftp_v1_ftp_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FtpStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_v1_ftp_what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FtpWhatIf"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FtpStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_v1_ftp_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FtpAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FtpStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_v1_readiness_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_v1_readiness__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_v1_readiness_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Body_recompute_v1_readiness_recompute_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stored_v1_plan_get: {
        parameters: {
            query?: {
                start?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_v1_plan_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlanPreviewRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_v1_plan_commit_post: {
        parameters: {
            query?: {
                today?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_v1_reports__kind__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "daily" | "weekly";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_report_v1_reports__kind__post: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: never;
            path: {
                kind: "daily" | "weekly";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_v1_reports__kind___stem__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "daily" | "weekly";
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_v1_jobs__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "sync" | "analyze" | "daily" | "weekly";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
        };
    };
    run_v1_autopilot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutopilotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_v1_autopilot_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutopilotRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
