"""initial schema

Revision ID: 08ad3e437f91
Revises:
Create Date: 2026-10-02 21:50:15.148757
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "08ad3e437f91"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strava_id", sa.Integer(), nullable=True),
        sa.Column("intervals_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("sex", sa.String(length=8), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("raw_strava_json", sa.JSON(), nullable=True),
        sa.Column("raw_intervals_json", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intervals_id"),
        sa.UniqueConstraint("strava_id"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.String(length=32), nullable=False),
        sa.Column("finished_at", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=True),
        sa.Column("rate_limit_snapshot", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("log_path", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.create_index("ix_job_runs_job_started", ["job", "started_at"], unique=False)

    op.create_table(
        "schema_meta",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("activity_type", sa.String(length=32), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("average_grade", sa.Float(), nullable=True),
        sa.Column("maximum_grade", sa.Float(), nullable=True),
        sa.Column("elevation_high", sa.Float(), nullable=True),
        sa.Column("elevation_low", sa.Float(), nullable=True),
        sa.Column("climb_category", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("starred", sa.Boolean(), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_cursors",
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("source", "key"),
    )
    op.create_table(
        "workout_templates",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("phase_tags", sa.JSON(), nullable=True),
        sa.Column("min_ftp_pct", sa.Float(), nullable=True),
        sa.Column("steps_template", sa.JSON(), nullable=True),
        sa.Column("duration_range_s", sa.JSON(), nullable=True),
        sa.Column("tss_formula", sa.String(length=200), nullable=True),
        sa.Column("indoor_ok", sa.Boolean(), nullable=False),
        sa.Column("outdoor_ok", sa.Boolean(), nullable=False),
        sa.Column("requires_power", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("id", "version"),
    )
    with op.batch_alter_table("workout_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workout_templates_id"), ["id"], unique=False)

    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=True),
        sa.Column("strava_id", sa.Integer(), nullable=True),
        sa.Column("intervals_id", sa.String(length=32), nullable=True),
        sa.Column("match_method", sa.String(length=16), nullable=False),
        sa.Column("sport_type", sa.String(length=32), nullable=False),
        sa.Column("is_ride", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_utc", sa.String(length=32), nullable=False),
        sa.Column("start_local", sa.String(length=40), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=True),
        sa.Column("moving_s", sa.Integer(), nullable=True),
        sa.Column("elapsed_s", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("elev_gain_m", sa.Float(), nullable=True),
        sa.Column("trainer", sa.Boolean(), nullable=False),
        sa.Column("commute", sa.Boolean(), nullable=False),
        sa.Column("race", sa.Boolean(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column("has_power", sa.Boolean(), nullable=False),
        sa.Column("has_hr", sa.Boolean(), nullable=False),
        sa.Column("has_cadence", sa.Boolean(), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("gear_id", sa.String(length=32), nullable=True),
        sa.Column("gear_name", sa.String(length=100), nullable=True),
        sa.Column("avg_w", sa.Float(), nullable=True),
        sa.Column("np_w", sa.Float(), nullable=True),
        sa.Column("max_w", sa.Float(), nullable=True),
        sa.Column("kj", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("avg_cad", sa.Float(), nullable=True),
        sa.Column("icu_training_load", sa.Float(), nullable=True),
        sa.Column("icu_intensity", sa.Float(), nullable=True),
        sa.Column("icu_ftp", sa.Float(), nullable=True),
        sa.Column("icu_eftp", sa.Float(), nullable=True),
        sa.Column("icu_pm_cp", sa.Float(), nullable=True),
        sa.Column("icu_pm_w_prime", sa.Float(), nullable=True),
        sa.Column("icu_pm_p_max", sa.Float(), nullable=True),
        sa.Column("icu_decoupling", sa.Float(), nullable=True),
        sa.Column("icu_polarization_index", sa.Float(), nullable=True),
        sa.Column("icu_joules_above_ftp", sa.Float(), nullable=True),
        sa.Column("icu_max_wbal_depletion", sa.Float(), nullable=True),
        sa.Column("icu_zone_times", sa.JSON(), nullable=True),
        sa.Column("icu_hr_zone_times", sa.JSON(), nullable=True),
        sa.Column("paired_event_id", sa.Integer(), nullable=True),
        sa.Column("icu_rpe", sa.Integer(), nullable=True),
        sa.Column("feel", sa.Integer(), nullable=True),
        sa.Column("raw_strava_json", sa.JSON(), nullable=True),
        sa.Column("raw_intervals_json", sa.JSON(), nullable=True),
        sa.Column("stage_flags", sa.JSON(), nullable=True),
        sa.Column("pending_detail", sa.Boolean(), nullable=False),
        sa.Column("pending_streams", sa.Boolean(), nullable=False),
        sa.Column("pending_analysis", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intervals_id"),
        sa.UniqueConstraint("strava_id"),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activities_athlete_id"), ["athlete_id"], unique=False)
        batch_op.create_index("ix_activities_is_ride_start", ["is_ride", "start_utc"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_activities_pending_analysis"), ["pending_analysis"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activities_pending_detail"), ["pending_detail"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activities_pending_streams"), ["pending_streams"], unique=False
        )
        batch_op.create_index("ix_activities_start_utc", ["start_utc"], unique=False)

    op.create_table(
        "athlete_settings_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("ftp", sa.Float(), nullable=True),
        sa.Column("indoor_ftp", sa.Float(), nullable=True),
        sa.Column("eftp", sa.Float(), nullable=True),
        sa.Column("w_prime", sa.Float(), nullable=True),
        sa.Column("p_max", sa.Float(), nullable=True),
        sa.Column("lthr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("power_zones", sa.JSON(), nullable=True),
        sa.Column("hr_zones", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("athlete_settings_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_athlete_settings_history_athlete_id"), ["athlete_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_athlete_settings_history_effective_from"),
            ["effective_from"],
            unique=False,
        )

    op.create_table(
        "fitness_daily",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("ctl_icu", sa.Float(), nullable=True),
        sa.Column("atl_icu", sa.Float(), nullable=True),
        sa.Column("tsb_icu", sa.Float(), nullable=True),
        sa.Column("ctl_sim", sa.Float(), nullable=True),
        sa.Column("atl_sim", sa.Float(), nullable=True),
        sa.Column("tsb_sim", sa.Float(), nullable=True),
        sa.Column("load_actual", sa.Float(), nullable=True),
        sa.Column("load_planned", sa.Float(), nullable=True),
        sa.Column("acwr_7_28", sa.Float(), nullable=True),
        sa.Column("monotony_7", sa.Float(), nullable=True),
        sa.Column("strain_7", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "date_local"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target", sa.JSON(), nullable=True),
        sa.Column("icu_event_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goals_athlete_id"), ["athlete_id"], unique=False)

    op.create_table(
        "power_curve_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("window", sa.String(length=16), nullable=False),
        sa.Column("durations_s", sa.JSON(), nullable=True),
        sa.Column("watts", sa.JSON(), nullable=True),
        sa.Column("w_kg", sa.JSON(), nullable=True),
        sa.Column("cp", sa.Float(), nullable=True),
        sa.Column("w_prime", sa.Float(), nullable=True),
        sa.Column("p_max", sa.Float(), nullable=True),
        sa.Column("eftp_icu", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "as_of_date", "window", "source"),
    )
    with op.batch_alter_table("power_curve_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_power_curve_snapshots_as_of_date"), ["as_of_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_power_curve_snapshots_athlete_id"), ["athlete_id"], unique=False
        )

    op.create_table(
        "readiness_daily",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("score_0_100", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("recommendation", sa.String(length=16), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("algo_version", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "date_local"),
    )
    op.create_table(
        "wellness_daily",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("ctl", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("ramp_rate", sa.Float(), nullable=True),
        sa.Column("ctl_load", sa.Float(), nullable=True),
        sa.Column("atl_load", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.Float(), nullable=True),
        sa.Column("hrv", sa.Float(), nullable=True),
        sa.Column("hrv_sdnn", sa.Float(), nullable=True),
        sa.Column("sleep_s", sa.Integer(), nullable=True),
        sa.Column("sleep_score", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("avg_sleeping_hr", sa.Float(), nullable=True),
        sa.Column("soreness", sa.Integer(), nullable=True),
        sa.Column("fatigue", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("mood", sa.Integer(), nullable=True),
        sa.Column("motivation", sa.Integer(), nullable=True),
        sa.Column("injury", sa.Integer(), nullable=True),
        sa.Column("readiness_icu", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("vo2max", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id", "date_local"),
    )
    op.create_table(
        "activity_intervals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=True),
        sa.Column("start_s", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("avg_w", sa.Float(), nullable=True),
        sa.Column("np_w", sa.Float(), nullable=True),
        sa.Column("intensity", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("avg_cad", sa.Float(), nullable=True),
        sa.Column("decoupling", sa.Float(), nullable=True),
        sa.Column("wbal_start", sa.Float(), nullable=True),
        sa.Column("wbal_end", sa.Float(), nullable=True),
        sa.Column("zone", sa.Integer(), nullable=True),
        sa.Column("training_load", sa.Float(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "source", "idx"),
    )
    with op.batch_alter_table("activity_intervals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_intervals_activity_id"), ["activity_id"], unique=False
        )

    op.create_table(
        "activity_metrics",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("algo_version", sa.String(length=32), nullable=False),
        sa.Column("np_w", sa.Float(), nullable=True),
        sa.Column("if_", sa.Float(), nullable=True),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.Column("vi", sa.Float(), nullable=True),
        sa.Column("tss_source", sa.String(length=16), nullable=True),
        sa.Column("ef", sa.Float(), nullable=True),
        sa.Column("decoupling_pct", sa.Float(), nullable=True),
        sa.Column("hr_lag_s", sa.Float(), nullable=True),
        sa.Column("hr_drift_detail", sa.JSON(), nullable=True),
        sa.Column("power_curve", sa.JSON(), nullable=True),
        sa.Column("time_in_zone_power", sa.JSON(), nullable=True),
        sa.Column("time_in_zone_hr", sa.JSON(), nullable=True),
        sa.Column("climbs", sa.JSON(), nullable=True),
        sa.Column("efforts", sa.JSON(), nullable=True),
        sa.Column("pacing", sa.JSON(), nullable=True),
        sa.Column("wbal_min_j", sa.Float(), nullable=True),
        sa.Column("estimated_power_meta", sa.JSON(), nullable=True),
        sa.Column("comparison", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("next_recommendation", sa.String(length=16), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("computed_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_table(
        "activity_zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("zone_type", sa.String(length=16), nullable=False),
        sa.Column("sensor_based", sa.Boolean(), nullable=True),
        sa.Column("custom_zones", sa.Boolean(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("distribution_buckets", sa.JSON(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_id", "zone_type"),
    )
    with op.batch_alter_table("activity_zones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_zones_activity_id"), ["activity_id"], unique=False
        )

    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seasons_athlete_id"), ["athlete_id"], unique=False)

    op.create_table(
        "segment_efforts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("start_utc", sa.String(length=32), nullable=True),
        sa.Column("start_index", sa.Integer(), nullable=True),
        sa.Column("end_index", sa.Integer(), nullable=True),
        sa.Column("elapsed_s", sa.Integer(), nullable=True),
        sa.Column("moving_s", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("avg_w", sa.Float(), nullable=True),
        sa.Column("device_watts", sa.Boolean(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("avg_cad", sa.Float(), nullable=True),
        sa.Column("pr_rank", sa.Integer(), nullable=True),
        sa.Column("kom_rank", sa.Integer(), nullable=True),
        sa.Column("achievements", sa.JSON(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("segment_efforts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_segment_efforts_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_segment_efforts_segment_id"), ["segment_id"], unique=False
        )

    op.create_table(
        "stream_files",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("hz", sa.Float(), nullable=False),
        sa.Column("original_size", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=True),
        sa.Column("n_samples", sa.Integer(), nullable=True),
        sa.Column("raw_json_path", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id"),
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("load_pattern", sa.String(length=8), nullable=False),
        sa.Column("focus", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "idx"),
    )
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blocks_season_id"), ["season_id"], unique=False)

    op.create_table(
        "plan_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("horizon_start", sa.Date(), nullable=True),
        sa.Column("horizon_end", sa.Date(), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plan_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plan_revisions_season_id"), ["season_id"], unique=False
        )

    op.create_table(
        "week_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("target_tss", sa.Float(), nullable=True),
        sa.Column("target_hours", sa.Float(), nullable=True),
        sa.Column("hit_sessions", sa.Integer(), nullable=True),
        sa.Column("planned_ctl_end", sa.Float(), nullable=True),
        sa.Column("template_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block_id", "week_start"),
    )
    with op.batch_alter_table("week_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_week_plans_block_id"), ["block_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_week_plans_week_start"), ["week_start"], unique=False)

    op.create_table(
        "planned_workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_plan_id", sa.Integer(), nullable=True),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("template_id", sa.String(length=64), nullable=True),
        sa.Column("template_version", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("workout_text", sa.Text(), nullable=True),
        sa.Column("target_tss", sa.Float(), nullable=True),
        sa.Column("target_duration_s", sa.Integer(), nullable=True),
        sa.Column("target_if", sa.Float(), nullable=True),
        sa.Column("indoor", sa.Boolean(), nullable=False),
        sa.Column("target_mode", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("icu_event_id", sa.Integer(), nullable=True),
        sa.Column("icu_training_load_readback", sa.Float(), nullable=True),
        sa.Column("executed_activity_id", sa.Integer(), nullable=True),
        sa.Column("compliance", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=8), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["executed_activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["week_plan_id"],
            ["week_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    with op.batch_alter_table("planned_workouts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_planned_workouts_athlete_id"), ["athlete_id"], unique=False
        )
        batch_op.create_index("ix_planned_workouts_date_slot", ["date_local", "slot"], unique=False)
        batch_op.create_index(batch_op.f("ix_planned_workouts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_planned_workouts_week_plan_id"), ["week_plan_id"], unique=False
        )

    op.create_table(
        "publish_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("planned_workout_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("icu_event_id", sa.Integer(), nullable=True),
        sa.Column("request", sa.JSON(), nullable=True),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("verified_load", sa.Float(), nullable=True),
        sa.Column("at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_workout_id"],
            ["planned_workouts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["job_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publish_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publish_log_planned_workout_id"), ["planned_workout_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_publish_log_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("publish_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publish_log_run_id"))
        batch_op.drop_index(batch_op.f("ix_publish_log_planned_workout_id"))

    op.drop_table("publish_log")
    with op.batch_alter_table("planned_workouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_planned_workouts_week_plan_id"))
        batch_op.drop_index(batch_op.f("ix_planned_workouts_status"))
        batch_op.drop_index("ix_planned_workouts_date_slot")
        batch_op.drop_index(batch_op.f("ix_planned_workouts_athlete_id"))

    op.drop_table("planned_workouts")
    with op.batch_alter_table("week_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_week_plans_week_start"))
        batch_op.drop_index(batch_op.f("ix_week_plans_block_id"))

    op.drop_table("week_plans")
    with op.batch_alter_table("plan_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_revisions_season_id"))

    op.drop_table("plan_revisions")
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blocks_season_id"))

    op.drop_table("blocks")
    op.drop_table("stream_files")
    with op.batch_alter_table("segment_efforts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_efforts_segment_id"))
        batch_op.drop_index(batch_op.f("ix_segment_efforts_activity_id"))

    op.drop_table("segment_efforts")
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seasons_athlete_id"))

    op.drop_table("seasons")
    with op.batch_alter_table("activity_zones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_zones_activity_id"))

    op.drop_table("activity_zones")
    op.drop_table("activity_metrics")
    with op.batch_alter_table("activity_intervals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_intervals_activity_id"))

    op.drop_table("activity_intervals")
    op.drop_table("wellness_daily")
    op.drop_table("readiness_daily")
    with op.batch_alter_table("power_curve_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_power_curve_snapshots_athlete_id"))
        batch_op.drop_index(batch_op.f("ix_power_curve_snapshots_as_of_date"))

    op.drop_table("power_curve_snapshots")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goals_athlete_id"))

    op.drop_table("goals")
    op.drop_table("fitness_daily")
    with op.batch_alter_table("athlete_settings_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_athlete_settings_history_effective_from"))
        batch_op.drop_index(batch_op.f("ix_athlete_settings_history_athlete_id"))

    op.drop_table("athlete_settings_history")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index("ix_activities_start_utc")
        batch_op.drop_index(batch_op.f("ix_activities_pending_streams"))
        batch_op.drop_index(batch_op.f("ix_activities_pending_detail"))
        batch_op.drop_index(batch_op.f("ix_activities_pending_analysis"))
        batch_op.drop_index("ix_activities_is_ride_start")
        batch_op.drop_index(batch_op.f("ix_activities_athlete_id"))

    op.drop_table("activities")
    with op.batch_alter_table("workout_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_templates_id"))

    op.drop_table("workout_templates")
    op.drop_table("sync_cursors")
    op.drop_table("segments")
    op.drop_table("schema_meta")
    with op.batch_alter_table("job_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_job_runs_job_started")

    op.drop_table("job_runs")
    op.drop_table("athletes")
    # ### end Alembic commands ###
