"""icu_events mirror

Revision ID: 6eba81126ed0
Revises: 08ad3e437f91
Create Date: 2026-10-02 22:02:12.154246
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6eba81126ed0"
down_revision: str | Sequence[str] | None = "08ad3e437f91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icu_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=True),
        sa.Column("start_date_local", sa.String(length=40), nullable=True),
        sa.Column("end_date_local", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("icu_training_load", sa.Float(), nullable=True),
        sa.Column("training_availability", sa.String(length=16), nullable=True),
        sa.Column("max_training_time", sa.Integer(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("icu_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_icu_events_external_id"), ["external_id"], unique=False
        )
        batch_op.create_index(
            "ix_icu_events_start_category", ["start_date_local", "category"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("icu_events", schema=None) as batch_op:
        batch_op.drop_index("ix_icu_events_start_category")
        batch_op.drop_index(batch_op.f("ix_icu_events_external_id"))

    op.drop_table("icu_events")
    # ### end Alembic commands ###
